name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm run build
      - name: GitHub Pages
        uses: crazy-max/ghaction-github-pages@v1.3.0
        with:
          # GitHub repository where assets will be deployed (default current)
          repo: master
          # Git branch where assets will be deployed
          target_branch: gh-pages
          # Create incremental commit instead of doing push force
          keep_history: false
          # Allow an empty commit to be created
          # allow_empty_commit: # optional, default is true
          # Build directory to deploy
          # build_dir:
          # Commit author's name
          # committer_name: # optional
          # Commit author's email
          # committer_email: # optional
          # Commit message
          # commit_message: # optional
          # Write the given domain name to the CNAME file
          fqdn: # optional
      env:
        CI: true
