name: Node.js CI

on:
  push:
    branches:
      - master

jobs:
  build:
    name: install
    runs-on: macOS-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          echo hello world
          npm run build
        env:
          CI: true
  deploy:
    needs: build
    name: GitHub Pages Deploy
    runs-on: macOS-latest
    steps:
      - name: GitHub Pages Deploy
      - uses: maxheld83/ghpages@v0.2.1
